name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build and Test with Maven
      timeout-minutes: 15
      run: ./mvnw -B verify

    - name: Get JaCoCo Coverage
      run: |
        python3 config/coverage.py target/site/jacoco/jacoco.csv

    - name: Fail if coverage has not improved
      run: |
        coverage=$(python3 config/coverage.py target/site/jacoco/jacoco.csv)
        echo "Coverage is $coverage"
        if [ $(echo "$coverage <= 24.456" | bc -l) -eq 1 ]; then
          echo "Coverage has not improved!"
          exit 1
        fi
      shell: bash
