name: Java CI with Maven

on:
  push:
  pull_request:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-java@v4.2.1
      with:
        distribution: 'temurin'
        java-version: '17'
        cache: 'maven'

    - name: Build and Test with Maven
      timeout-minutes: 15
      run: ./mvnw -B verify

    - name: Get JaCoCo Coverage
      id: coverage  
      run: |
        coverage=$(python3 coverage_check.py target/site/jacoco/jacoco.csv)
        echo "::set-output name=coverage::$coverage"

    - name: Fail if coverage is less than 70%
      run: |
        coverage=${{ steps.coverage.outputs.coverage }}
        if (( $(echo "$coverage < 24.46" | bc -l) )); then
          echo "Coverage has not improved."
          exit 1
        fi
      shell: bash
